trigger:
  - main  # Trigger pipeline when changes are pushed to the main branch

pool:
  vmImage: ubuntu-latest  # Use a hosted Ubuntu agent

steps:
# Step 1: Checkout the code from GitHub
- checkout: self

# Step 2: Set up Node.js environment
- task: UseNode@1
  inputs:
    version: '18.x'  # Use Node.js 18 LTS

# Step 3: Install npm dependencies (if you have a package.json)
- script: |
    npm install
  displayName: 'Install npm dependencies'

# Step 4: (Optional) Build step, if you have a build script
# - script: |
#     npm run build
#   displayName: 'Build the app'

# Step 5: (Optional) Run tests, if you want to keep testing
# - script: |
#     npm test
#   displayName: 'Run tests'
