# azure-pipelines.yml

trigger:
  - main  # or use '*' to run for all branches

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '18.x'  # change based on your project requirements

  - script: |
      echo "Installing dependencies..."
      npm install
    displayName: 'Install dependencies'

  - script: |
      echo "Running build..."
      npm run build
    displayName: 'Build project'

  - script: |
      echo "Running tests..."
      npm test
    displayName: 'Run tests'
